// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOfuGfhfD7c1NHHFjwyDVDkVllJoWCz_s',
    appId: '1:228815382617:web:bc2cf78d3e4c85fcda2948',
    messagingSenderId: '228815382617',
    projectId: 'tlaloc-3c65c',
    authDomain: 'tlaloc-3c65c.firebaseapp.com',
    databaseURL: 'https://tlaloc-3c65c-default-rtdb.firebaseio.com',
    storageBucket: 'tlaloc-3c65c.appspot.com',
    measurementId: 'G-2VG3LXHV9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUwkYNkdvsnappHUPiiVQcYpfFdZ8vDrs',
    appId: '1:228815382617:android:31bfcfba094db7ffda2948',
    messagingSenderId: '228815382617',
    projectId: 'tlaloc-3c65c',
    databaseURL: 'https://tlaloc-3c65c-default-rtdb.firebaseio.com',
    storageBucket: 'tlaloc-3c65c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTMk5qWvkMU8VpzXW-9JgxTXLuj1PEQvw',
    appId: '1:228815382617:ios:efb20394c7978b06da2948',
    messagingSenderId: '228815382617',
    projectId: 'tlaloc-3c65c',
    databaseURL: 'https://tlaloc-3c65c-default-rtdb.firebaseio.com',
    storageBucket: 'tlaloc-3c65c.appspot.com',
    androidClientId: '228815382617-7ap23qdeu0g4v0i068cr6lor4l3a4air.apps.googleusercontent.com',
    iosClientId: '228815382617-6befg3ke4p12a7ggddlu3evjisj9g0pt.apps.googleusercontent.com',
    iosBundleId: 'com.example.tlaloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTMk5qWvkMU8VpzXW-9JgxTXLuj1PEQvw',
    appId: '1:228815382617:ios:efb20394c7978b06da2948',
    messagingSenderId: '228815382617',
    projectId: 'tlaloc-3c65c',
    databaseURL: 'https://tlaloc-3c65c-default-rtdb.firebaseio.com',
    storageBucket: 'tlaloc-3c65c.appspot.com',
    androidClientId: '228815382617-7ap23qdeu0g4v0i068cr6lor4l3a4air.apps.googleusercontent.com',
    iosClientId: '228815382617-6befg3ke4p12a7ggddlu3evjisj9g0pt.apps.googleusercontent.com',
    iosBundleId: 'com.example.tlaloc',
  );
}
